spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      idle-timeout: 100
      max-lifetime: 100
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.default_batch_fetch_size: 150
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
  sql:
    init:
      mode: always

redis:
  poll-timeout:
    image-download: 10

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.sql: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE